host: 0.0.0.0
port: 4000
title: Кружки по математике от Ильи Глебовича.
baseurl: "/apo"
email: mylntsa.ilya.63@gmail.com
description: >
  Страница кружков по математике, которые ведёт Илья Глебович.
  
#detach: true
github_username:  ilya-ilya

# Build settings
markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass
