host: 0.0.0.0
port: 4000
title: Ознакомительный курс низкоуровневых архитектур от Ильи Глебовича.
baseurl: "/okna"
email: mylntsa.ilya.63@gmail.com
description: >
  Страница ознакомительный курса низкоуровневых архитектур, который ведёт Илья Глебович.
  
#detach: true
github_username:  ilya-ilya

# Build settings
markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass
